apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: redis-gcp-storage
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
  replication-type: none
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
reclaimPolicy: Delete
