apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: queue
spec:
  type: ClusterIP
  selector:
    app: queue
  ports:
    - name: queue
      port: 5672
      targetPort: queue-port
      protocol: TCP
    - name: mgmt
      port: 15672
      targetPort: mgmt-port
      protocol: TCP
