apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: auth
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 50%
  template:
    metadata:
      labels:
        app: auth
    spec:
      serviceAccountName: ksa-auth
      containers:
        - name: auth
          image: asia-east1-docker.pkg.dev/cnad-group3/cnad-prod-repo/auth:latest
          imagePullPolicy: Always
          command: ["/bin/sh"]
          args:
            - "-c"
            - |
              export JWT_TOKEN=$(cat /mnt/secrets-store/jwt-token) && \
              npm run start --silent
          resources:
            limits:
              cpu: 200m
              memory: 1Gi
            requests:
              cpu: 10m
              memory: 150Mi
          ports:
            - name: auth-port
              containerPort: 8000
          livenessProbe:
            httpGet:
              path: /api/healthy
              port: 8000
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 60
            failureThreshold: 1
          readinessProbe:
            httpGet:
              path: /api/healthy
              port: 8000
            initialDelaySeconds: 20
            timeoutSeconds: 2
            periodSeconds: 20
            failureThreshold: 1
          env:
            - name: PORT
              value: "8000"
            - name: API_VERSION
              value: "v1"
            - name: CLIENT_URL
              value: "https://cnad.info"
            - name: API_GATEWAY_URL
              value: "gateway.gateway.svc.cluster.local:8000"
            - name: RABBITMQ_ENDPOINT
              value: amqp://admin:admin@rabbitmq.queue.svc.cluster.local:5672
            - name: DATABASE_HOST
              value: postgres-auth-0.postgres-auth.postgres-auth.svc.cluster.local
            - name: DATABASE_USER
              value: admin
            - name: DATABASE_PASSWORD
              value: admin
            - name: DATABASE_NAME
              value: auth
            - name: DATABASE_PORT
              value: "5432"
          volumeMounts:
            - name: secret-volume
              mountPath: /mnt/secrets-store
              readOnly: true
      volumes:
        - name: secret-volume
          csi:
            driver: secrets-store-gke.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: auth-secret
