apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: auth-secret
  namespace: auth
spec:
  provider: gke
  parameters:
    secrets: |
      - resourceName: "projects/cnad-group3/secrets/jwt-token/versions/latest"
        path: "jwt-token"
