apiVersion: v1
kind: Service
metadata:
  name: auth
  namespace: auth
spec:
  type: ClusterIP
  selector:
    app: auth
  ports:
    - name: auth
      port: 8000
      targetPort: auth-port
      protocol: TCP
