apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingressgateway
  namespace: istio-system
  annotations:
    kubernetes.io/ingress.class: gce
    kubernetes.io/ingress.global-static-ip-name: istio-ingress-ip
spec:
  defaultBackend:
    service:
      name: istio-ingressgateway
      port:
        number: 80
