apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gateway
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 50%
  template:
    metadata:
      labels:
        app: gateway
    spec:
      serviceAccountName: ksa-gateway
      containers:
        - name: gateway
          image: asia-east1-docker.pkg.dev/cnad-group3/cnad-prod-repo/gateway:latest
          imagePullPolicy: Always
          command: ["/bin/sh"]
          args:
            - "-c"
            - |
              export SECRET_KEY=$(cat /mnt/secrets-store/secret-key) && \
              export JWT_TOKEN=$(cat /mnt/secrets-store/jwt-token) && \
              npm run start --silent
          resources:
            limits:
              cpu: 200m
              memory: 1Gi
            requests:
              cpu: 10m
              memory: 150Mi
          ports:
            - name: gateway-port
              containerPort: 8000
          livenessProbe:
            httpGet:
              path: /api/healthy
              port: 8000
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 60
            failureThreshold: 1
          readinessProbe:
            httpGet:
              path: /api/healthy
              port: 8000
            initialDelaySeconds: 20
            timeoutSeconds: 2
            periodSeconds: 20
            failureThreshold: 1
          env:
            - name: PORT
              value: "8000"
            - name: API_VERSION
              value: "v1"
            - name: CLIENT_URL
              value: "https://cnad.info"
            - name: AUTH_BASE_URL
              value: "http://auth.auth.svc.cluster.local:8000"
            - name: REDIS_HOST
              value: "redis-0.redis.redis.svc.cluster.local"
            - name: REDIS_PASSWORD
              value: "redispassword"
            - name: REDIS_PORT
              value: "6379"
          volumeMounts:
            - name: secret-volume
              mountPath: /mnt/secrets-store
              readOnly: true
      volumes:
        - name: secret-volume
          csi:
            driver: secrets-store-gke.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: gateway-secret