apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: gateway
  annotations:
    cloud.google.com/neg: '{"exposed_ports": {"8000":{"name": "cnad-prod-neg"}}}'
spec:
  type: ClusterIP
  selector:
    app: gateway
  ports:
    - name: gateway
      port: 8000
      targetPort: gateway-port
      protocol: TCP
