apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: notification-secret
  namespace: notification
spec:
  provider: gke
  parameters:
    secrets: |
      - resourceName: "projects/cnad-group3/secrets/sender-email/versions/latest"
        path: "sender-email"
      - resourceName: "projects/cnad-group3/secrets/sender-email-password/versions/latest"
        path: "sender-email-password"
