apiVersion: v1
kind: Service
metadata:
  name: notification
  namespace: notification
spec:
  type: ClusterIP
  selector:
    app: notification
  ports:
    - name: notification
      port: 8000
      targetPort: noti-port
      protocol: TCP
