apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-auth-config
  namespace: postgres-auth
data:
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: admin
  POSTGRES_DB: auth
  PGDATA: /var/lib/postgresql/data/pgdata
