apiVersion: v1
kind: Service
metadata:
  name: postgres-auth
  namespace: postgres-auth
spec:
  clusterIP: None
  selector:
    app: postgres-auth
  ports:
    - name: postgres-auth
      port: 5432
      targetPort: pg-auth-port
      protocol: TCP
