apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: api-virtualservice
  namespace: istio-system
spec:
  hosts:
    - "*"
  gateways:
    - istio-ingressgateway
  http:
    - route:
        - destination:
            host: gateway.gateway.svc.cluster.local
            port:
              number: 8000
