apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: backend-secret
  namespace: backend
spec:
  provider: gke
  parameters:
    secrets: |
      - resourceName: "projects/cnad-group3/secrets/secret-key/versions/latest"
        path: "secret-key"
      - resourceName: "projects/cnad-group3/secrets/jwt-token/versions/latest"
        path: "jwt-token"
