apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: postgres-auth-gcp-storage
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
  replication-type: none
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
allowVolumeExpansion: true
