apiVersion: v1
kind: Namespace
metadata:
  name: gateway
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: notification
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: auth
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: backend
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: postgres-auth
---
apiVersion: v1
kind: Namespace
metadata:
  name: postgres-backend
---
apiVersion: v1
kind: Namespace
metadata:
  name: queue
---
apiVersion: v1
kind: Namespace
metadata:
  name: redis
---
