apiVersion: v1
kind: Namespace
metadata:
  name: gateway
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: notification
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: auth
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: backend
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: postgres-auth
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: postgres-backend
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: queue
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: redis
  labels:
    istio-injection: enabled
---

