apiVersion: v1
kind: Service
metadata:
  name: postgres-backend
  namespace: postgres-backend
spec:
  clusterIP: None
  selector:
    app: postgres-backend
  ports:
    - name: postgres-backend
      port: 5432
      targetPort: pg-be-port
      protocol: TCP
