apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: postgres-backend-local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
allowVolumeExpansion: true
