apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-control-plane
  namespace: istio-system
spec:
  profile: minimal
  components:
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        label:
          app: istio-ingressgateway
          istio: ingressgateway
        k8s:
          service:
            type: ClusterIP
            ports:
              - name: status-port
                port: 15021
                targetPort: 15021
              - name: http
                port: 80
                targetPort: 8080
          serviceAnnotations:
            cloud.google.com/neg: '{"ingress": true, "exposed_ports":{"80":{}}}'
