name: Update kubernetes settings in GCP

# only run on main branch and /gcp file changes
# on:
#   push:
#     branches:
#       - main
#     paths:
#       - 'gcp/**'

# jobs:
#   update-k8s:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Set up Google Cloud SDK
#         uses: google-github-actions/setup-gcloud@v2
#         with:
#           version: 'latest'
#           project_id: ${{ secrets.GCP_PROJECT_ID }}
#           service_account_key: ${{ secrets.GCP_SA_KEY }}
#           export_default_credentials: true

#       - name: Update Kubernetes settings
#         run: |
#           gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER_NAME }} --zone ${{ secrets.GKE_ZONE }} --project ${{ secrets.GCP_PROJECT_ID }}

#       - name: Apply Kubernetes configurations
#         run: |
#           run.sh --prd